### ISSUE TITLE
Include plugin API before loading `load-early.php`

### ISSUE THREAD

**Issue by nprasath002** [humanmade/altis-cms#291] opened 2020-12-02 09:31 UTC
We need to truncate messages sent to x-ray to get rid of PHP warning mentioned in the issue above.

The first action fired in altis is `do_action( 'altis.loaded_autoloader' );` resulting in sending traces to x-ray. The mu-plugins are loaded after this action hook in `wp-settings.php`.

To filter x-ray traces we can add filters in `.config/load-early.php` but plugin API is not loaded at this point.

See the following code segment

```
// Load an escape hatch early load file, if it exists.
if ( file_exists( __DIR__ . '/.config/load-early.php' ) ) {
	require_once __DIR__ . '/.config/load-early.php';
}

// Load the plugin API (like add_action etc) early, so everything loaded
// via the Composer autoloaders can using actions.
require_once __DIR__ . '/wordpress/wp-includes/plugin.php';

// Load the whole autoloader very early, this will also include
// all `autoload.files` from all modules.
require_once __DIR__ . '/vendor/autoload.php';

// Load all modules.
require_once __DIR__ . '/vendor/modules.php';

do_action( 'altis.loaded_autoloader' );
```

Loading plugin API before `load-early.php` file will fix the issue and enable us to add filters/actions inside the file.

Proposed solution

```
// Load the plugin API (like add_action etc) early, so everything loaded
// via the Composer autoloaders can using actions.
require_once __DIR__ . '/wordpress/wp-includes/plugin.php';

// Load an escape hatch early load file, if it exists.
if ( file_exists( __DIR__ . '/.config/load-early.php' ) ) {
	require_once __DIR__ . '/.config/load-early.php';
}


// Load the whole autoloader very early, this will also include
// all `autoload.files` from all modules.
require_once __DIR__ . '/vendor/autoload.php';

// Load all modules.
require_once __DIR__ . '/vendor/modules.php';

do_action( 'altis.loaded_autoloader' );
```

**Comment by rmccue** [comment] 2020-12-02 11:27
`load-early.php` is really intended only as an escape hatch, and is intentionally before we load anything else, so this is by design. Using `load-early.php` should be avoided wherever possible for this and other reasons.

If there's issues with X-Ray warnings, those should be fixed in Altis rather than worked around in your code.

(Also, this is a public repo, please ensure you scrub client names before posting :))

**Closed by rmccue** 2020-12-02 11:27 UTC
Labels: enhancement
